spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/love?useSSL=true
      driver-class-name: com.mysql.jdbc.Driver
      password: root
      username: root
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      pool-prepared-statements: true  #打开pscache，并且指定每个连接上pscache的大小
      max-pool-prepared-statement-per-connection-size: 20
      filter: stat,wall,log4j   #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true

      # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
      #是否启用StatFilter默认值true
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
        session-stat-enable: false
        session-stat-max-count: 1000
        principal-session-name: admin
        principal-cookie-name: admin
        profile-enable: true
      # StatViewServlet配置
      #展示Druid的统计信息,StatViewServlet的用途包括：1.提供监控信息展示的html页面2.提供监控信息的JSON API
      #是否启用StatViewServlet默认值true
      stat-view-servlet:
        enabled: true
        #根据配置中的url-pattern来访问内置监控页面，如果是上面的配置，内置监控页面的首页是/druid/index.html例如：
        #http://110.76.43.235:9000/druid/index.html
        #http://110.76.43.235:8080/mini-web/druid/index.html
        url-pattern: /druid/*
        #允许清空数据
        reset-enable: true
        login-username: admin
        login-password: admin
        #StatViewSerlvet展示出来的监控信息比较敏感，是系统运行的内部情况，如果你需要做访问控制，可以配置allow和deny这两个参数
        #deny优先于allow，如果在deny列表中，就算在allow列表中，也会被拒绝。如果allow没有配置或者为空，则允许所有访问配置的格式
        #<IP>
        #或者<IP>/<SUB_NET_MASK_size>其中128.242.127.1/24
        #24表示，前面24位是子网掩码，比对的时候，前面24位相同就匹配,不支持IPV6。
        allow:
        deny: 127.0.0.1
      # Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
      aop-patterns: com.love.lylph.service.*
    type: com.alibaba.druid.pool.DruidDataSource
  output:
    ansi:
      enabled: always
  aop:
    proxy-target-class: true


mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.love.lylph.pojo
  mapper-locations: classpath:mapper/*.xml


server:
  port: 8082
  tomcat:
    uri-encoding: UTF-8


logging:
  path: C:/Users/sipaote/Desktop/logs
  pattern:
    console: '[%-5p] %d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] -- method:%m%n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n'

